name = "eventplanning"
compatibility_date = "2026-06-17"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "event-planning"
database_id = "61895519-8ca0-4d99-a0a5-a3a354f04e99"
